# -*- coding: utf-8 -*-
#
# Configuration Program documentation build configuration file, created by
# sphinx-quickstart on Fri Jul 26 10:43:58 2019.
#
# This file is execfile()d with the current directory set to its
# containing dir.
#
# Note that not all possible configuration values are present in this
# autogenerated file.
#
# All configuration values have a default; values that are commented out
# serve to show the default.

# If extensions (or modules to document with autodoc) are in another directory,
# add these directories to sys.path here. If the directory is relative to the
# documentation root, use os.path.abspath to make it absolute, like shown here.
#
# import os
# import sys
# sys.path.insert(0, os.path.abspath('.'))

import importlib
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))

from conf_common import (
    enable_spelling_extension,
    get_spelling_word_list,
    load_linkcheck_ignore,
)


# -- General configuration ------------------------------------------------

# If your documentation needs a minimal Sphinx version, state it here.
#
# needs_sphinx = '1.0'

# Add any Sphinx extension module names here, as strings. They can be
# extensions coming with Sphinx (named 'sphinx.ext.*') or your custom
# ones.
extensions = ['sphinx.ext.autodoc',
    'sphinx.ext.todo',
    'sphinx.ext.ifconfig',
    'sphinx.ext.viewcode',
    'sphinx_sitemap',
    'rst2pdf.pdfbuilder']
extensions = enable_spelling_extension(extensions)

if 'tags' in globals():
    # Use a distinct tag for the J build to avoid including winsyslog-only sections
    tags.add('winsyslog_j')

# Add any paths that contain templates here, relative to this directory.
templates_path = ['_templates']

# The suffix(es) of source filenames.
# You can specify multiple suffix as a list of string:
#
# source_suffix = ['.rst', '.md']
source_suffix = '.rst'

# The master toctree document.
master_doc = 'index.winsyslog-j'

# General information about the project.
project = u'WinSyslog'
copyright = u'2025, Adiscon GmbH'
author = u'Adiscon GmbH'

# The version info for the project you're documenting, acts as replacement for
# |version| and |release|, also used in various other places throughout the
# built documents.
#
# The short X.Y version.
version = u'18.0'
# The full version, including alpha/beta/rc tags.
release = u'18.0'

# The language for content autogenerated by Sphinx. Refer to documentation
# for a list of supported languages.
#
# This is also used if you do content translation via gettext catalogs.
# Usually you set "language" from the command line for these cases.
language = 'en'

linkcheck_ignore = load_linkcheck_ignore(__file__)
spelling_word_list_filename = get_spelling_word_list(__file__)

# List of patterns, relative to source directory, that match files and
# directories to ignore when looking for source files.
# This patterns also effect to html_static_path and html_extra_path
# Here are all rst files that are not necessary for the Winsyslog-doc 
exclude_patterns = ['articles/index-mwagent.rst','articles/include-event-id-in-syslog-msg.rst',
   'mwagentspecific/index.rst','mwagentspecific/actions.rst',
   'mwagentspecific/configuringmwagent.rst','mwagentspecific/filterconditions.rst','mwagentspecific/generaloptions.rst',
   'mwagentspecific/services.rst',
   'mwagentspecific/a-controlntservice.rst','mwagentspecific/a-forwardsyslogoptions.rst',
   'mwagentspecific/a-httprequest.rst','mwagentspecific/a-syslogqueueaction.rst','mwagentspecific/cpumonitor.rst',
   'mwagentspecific/databasemonitor.rst','mwagentspecific/diskspacemonitor.rst',
   'mwagentspecific/eventlogmonitorv1.rst','mwagentspecific/eventlogmonitorv2.rst','mwagentspecific/f-cpumemorymonitor.rst',
   'mwagentspecific/f-diskspacemonitor.rst','mwagentspecific/f-ftpprobe.rst','mwagentspecific/f-httpprobe.rst',
   'mwagentspecific/f-imapprobe.rst','mwagentspecific/f-nntpprobe.rst','mwagentspecific/f-ntservicemonitor.rst',
   'mwagentspecific/f-pop3probe.rst','mwagentspecific/f-serialportmonitor.rst','mwagentspecific/f-smtpprobe.rst',
   'mwagentspecific/filemonitor.rst','mwagentspecific/ftpprobe.rst','mwagentspecific/httpprobe.rst',
   'mwagentspecific/imapprobe.rst','mwagentspecific/monitorwareechorequest.rst','mwagentspecific/nntpprobe.rst',
   'mwagentspecific/ntservicemonitor.rst','mwagentspecific/passivesysloglistener.rst','mwagentspecific/pingprobe.rst',
   'mwagentspecific/pop3probe.rst','mwagentspecific/portprobe.rst','mwagentspecific/serialportmonitor.rst',
   'mwagentspecific/smtplistener.rst','mwagentspecific/smtpprobe.rst','mwagentspecific/snmpmonitor.rst',
   'eventreporterspecific/*.rst','eventreporterspecific/faq/*.rst','gettingstarted/index.rst',
#'gettingstarted/alarmingvianetsend.rst',
   'gettingstarted/creatinganinitialconfiguration.rst',
#'gettingstarted/emailnotifications.rst',
   'gettingstarted/filterconditions.rst','gettingstarted/installation.rst','gettingstarted/loggingevents.rst',
   'gettingstarted/monitoringexternaldevicesping.rst','gettingstarted/monitoringexternaldevicesportprobe.rst',
   'gettingstarted/monitoringftpserver.rst','gettingstarted/monitoringharddiskspace.rst','gettingstarted/monitoringimapserver.rst',
   'gettingstarted/monitoringnntpserver.rst','gettingstarted/monitoringsmtpserver.rst','gettingstarted/startingscriptsandapplications.rst',
   'gettingstarted/monitorwareagenttutorial.rst','gettingstarted/obtainingaprintablemanual.rst','gettingstarted/timebasedfilters.rst',
   'glossaryofterms/index.rst',
   'introduction/index.rst','introduction/core-components.rst','introduction/features.rst','introduction/system-requirements.rst',
#'gettingstarted/ignoringevents.rst',
#'producttour/*.rst',
   'producttour/index.rst','producttour/cpumemorymonitor.rst','producttour/databasemonitor.rst','producttour/diskspacemonitor.rst',
   'producttour/eventlogmonitor.rst','producttour/eventlogmonitorv2.rst','producttour/filemonitor.rst','producttour/ftpprobe.rst',
   'producttour/httpprobe.rst',
   'producttour/imapprobe.rst','producttour/nntpprobe.rst','producttour/ntservicesmonitor.rst','producttour/otherfeatures.rst',
   'producttour/pingprobe.rst','producttour/pop3probe.rst','producttour/portprobe.rst','producttour/serialportmonitor.rst',
   'producttour/smtpprobe.rst',
   'producttour/testpassivesyslogservice.rst','producttour/powerfulleventprocessing.rst',
   'references/index.rst','references/mwagentshortcutkeys.rst','references/mwagentservice2.rst','references/icmpcodes.rst',
   'rsyslogwaspecific/*.rst','rsyslogwaspecific/faq/start-program-action-troubleshooting.rst','references/editioncomparison.rst',
   'rsyslogwaspecific/faq/config-reload-high-load.rst','rsyslogwaspecific/faq/openssl-cve-impact.rst',
   'index.eventreporter.rst','index.mwagent.rst','index.rsyslog.rst',
   'stepbystepguides.rst','purchasingmwagent.rst','monitorwareconcepts.rst','commonuses.rst','gettinghelp.rst',
   'index.syslogviewer.rst','index.winsyslog.rst','winsyslogspecific/winsyslog.rst','winsyslogspecific/generaloptions.rst',
   'winsyslogspecific/postprocessapps-options.rst','mwagentspecific/general-options.rst','winsyslogspecific/configuringwinsyslog.rst',
   'gettingstarted/multiple-rulesets-rules-actions.rst','winsyslogspecific/generaloptions.rst','winsyslogspecific/general-options.rst',
   'mwagentspecific/faq.rst','mwagentspecific/faq/*.rst'
]

# The name of the Pygments (syntax highlighting) style to use.
pygments_style = 'sphinx'

# If true, `todo` and `todoList` produce output, else they produce nothing.
todo_include_todos = True



# -- Options for HTML output ----------------------------------------------

# The theme to use for HTML and HTML Help pages.  See the documentation for
# a list of builtin themes.
#
# Base URL for sitemap generation
html_baseurl = 'https://www.winsyslog.com/files/manual/current/'

# Sitemap configuration to remove language/version from URLs
sitemap_url_scheme = "{link}"
sitemap_localtolinks = False
sitemap_filename = "sitemap.xml"

if importlib.util.find_spec("furo") is not None:
    html_theme = "furo"
    html_theme_options = {
        # Furo theme options (removed 'show_related' as it's not supported)
        "sidebar_hide_name": False,
        "light_css_variables": {
            "color-brand-primary": "#336699",
            "color-brand-content": "#336699",
        },
        "dark_css_variables": {
            "color-brand-primary": "#5599dd",
            "color-brand-content": "#5599dd",
        },
    }
else:
    html_theme = "alabaster"
    html_theme_options = {}

# Add any paths that contain custom static files (such as style sheets) here,
# relative to this directory. They are copied after the builtin static files,
# so a file named "default.css" will overwrite the builtin "default.css".
# html_static_path = ['_static']
# needs to be set, otherwise the folder _static is searched in the same folder where the conf.py is located. 
#html_static_path = ['../_static']
#is not needed at the moment but causes problems if it stays as an empty folder because git does not add empty folders

# Custom sidebar templates, must be a dictionary that maps document names
# to template names.
#
# Furo theme has its own sidebar system, so we remove the custom sidebars
# or use Furo-compatible ones
# html_sidebars = {
#     '**': [
#         'about.html',          # Not available in Furo
#         'relations.html',      # Not available in Furo
#         'globaltoc.html',      # Built into Furo
#         'searchbox.html',      # Built into Furo
#     ]
# }


# -- Options for HTMLHelp output ------------------------------------------

# Output file base name for HTML help builder.
htmlhelp_basename = 'WinSyslog'


# -- Options for LaTeX output ---------------------------------------------

latex_elements = {
    # The paper size ('letterpaper' or 'a4paper').
    #
    # 'papersize': 'letterpaper',

    # The font size ('10pt', '11pt' or '12pt').
    #
    # 'pointsize': '10pt',

    # Additional stuff for the LaTeX preamble.
    #
    # 'preamble': '',

    # Latex figure (float) alignment
    #
    # 'figure_align': 'htbp',
}

# Grouping the document tree into LaTeX files. List of tuples
# (source start file, target name, title,
#  author, documentclass [howto, manual, or own class]).
latex_documents = [
    (master_doc, 'WinSyslog.tex', u'WinSyslog Configuration Documentation',
     u'Adiscon GmbH', 'manual'),
]


# -- Options for manual page output ---------------------------------------

# One entry per manual page. List of tuples
# (source start file, name, description, authors, manual section).
man_pages = [
    (master_doc, 'WinSyslog', u'WinSyslog Configuration Documentation',
     [author], 1)
]


# -- Options for Texinfo output -------------------------------------------

# Grouping the document tree into Texinfo files. List of tuples
# (source start file, target name, title, author,
#  dir menu entry, description, category)
texinfo_documents = [
    (master_doc, 'WinSyslog', u'WinSyslog Configuration Documentation',
     author, 'WinSyslog', 'An enhanced syslog server for windows.',
     'System Tools'),
]



# -- Options for PDF output -------------------------------------------

pdf_documents = [
    (master_doc, u'WinSyslog-J', u'WinSyslog Configuration Documentation',
     author, 'WinSyslog', 'An enhanced syslog server for windows.',
     'System Tools'),
]


